---
title: "20180224"
date: 2018-02-24T01:10:00-04:00
draft: false
---

* News

** [[http://www.ultimasnoticias.com.ve/noticias/comunidad/inac-crea-sistema-automatizado-rebibir-dencuncias-incumplimiento-aerolineas/][INAC crea sistema automatizado para rebibir dencuncias por incumplimiento de aerolíneas]]
Published: 24 febrero, 2018 3:20 pm

.-El Instituto Nacional de Aeronáutica Civil  informó este sábado a través de la
red social de Twitter, la creación del para recibir denuncias por parte de los
pasajeros por el incumplimiento de las aerolíneas.Los usuarios que deseen
realizar denuncias deberán ingresar a la página web

** [[http://www.ultimasnoticias.com.ve/noticias/deportes/ocean-bay-vendra-duro-al-final/][Ocean Bay vendrá duro al final]]
Published: 23 febrero, 2018 5:29 pm

“ está excelente tras superar sus lesiones en el tendón y su fractura en la
caña”, señaló su entrenador Advirtió que decidieron inscribirlo para el lunes
26, pese a que varió la distancia del Clásico Hylander, pues era en 1.400 metros
y luego en 1.200. Dijo: “el caballo está muy bien y con el respeto que me
inspiran los rivales y la reaparición, si responde a lo que él es, será duro
rival al final”.. Reapareció el 11 de junio de 2017 y triunfó en 1.200 metros.
No actúa desde entonces.La potra Visionaria debutó con una victoria en 1.300,
por 16 cuerpos en 1’18”. Ramón García indicó: “Fue muy buen estreno. Vamos a
ligar que la salud la acompañe. Lamentablemente la programación no nos ayuda. ”,
concluyó.

** [[http://www.ultimasnoticias.com.ve/noticias/slider/kid-rodriguez-supero-primera-prueba/][El “Kid” Rodríguez superó primera prueba]]
Published: 24 febrero, 2018 11:22 am

.- Francisco Rodríguez tiene tarea pendiente para 2018, pues debe demostrar que
aún es un relevista élite tras los traspiés que tuvo la campaña pasada, cuando
fue dejado en libertad por los Tigres de Detroit y, posteriormente, los
Nacionales de Washington.El “” empezó el curso con los , con quienes busca un
cupo en el róster de 25 para el día inaugural, con el pie derecho.El caraqueño
retiró el quinto episodio del primer compromiso de los cuáqueros en la Liga de
la Toronja, contra los Piratas de Pittsburgh, sin mayores inconvenientes aunque
empezó con cuatro bolas malas consecutivas ante Gift Ngoepe.Sin embargo, sacó la
casta. Esa que lo hace acreedor de 437 salvados en la gran carpa y enderezó el
camino.El “Kid” solo necesitó siete envíos para sacar la entrada, pese a que
Richard Ureña le sonó indiscutible al derecho.cabrera tronó sencilloMiguel
Cabrera quiere empezar el 2018 por lo alto y aunque no pudo mostrar su fuerza,
si logró exhibir que puede darle sólido a la pelota.El maracayero, quien ayer
fungió como bateador designado de los Tigres de Detroit en los inicios de los
juegos primaverales, conectó hit al jardín derecho ante un lanzamiento del
derecho Ben Heller en su segundo turno del encuentro.En su primera aparición
oficial en la Liga de la Toronja en 2018, Cabrera falló con un rolling a la
tercera base.

** [[http://www.ultimasnoticias.com.ve/noticias/slider/cien-anos-magallanes-salto-al-campo-primera-vez/][Hace cien años Magallanes saltó al campo por primera vez]]
Published: 24 febrero, 2018 6:15 am

Si bien es cierto que el pasado 26 de octubre de conmemoró un siglo de la
fundación de los Navegantes del Magallanes, es este sábado 24 de febrero cuando
se celebran los primeros cien años del estreno de este popular club en el campo
de juego, aunque solo se puede asociar desde el punto de vista de mercadeo con
el club que compite actualmente en la pelota profesional local.En una fecha como
la de hoy, en el año 1918, debutó el conjunto creado cuatro meses antes con una
junta directiva que  integraron Jesús Gómez (presidente, Miguel Antonio Ponce
(vicepresidente), Antonio Benítez (tesorero), Luis Belisario (secretario de
actas), Hugues Alfonso (secretario de correspondencia), Avelino Issa (inspector
general) y en calidad de vocales Florencio Guinaglia, Napoleón Caglianone y
Pedro Solares.Es ese encuentro del campeonato de tercera categoría que se
disputó en el Stand Base Ball capitalino, en Quebrada Honda, Magallanes cayó  20
carreras por 9 ante Flor del Ávila, con una alineación integrada por Emilio
Meneses (P),_Marcos Moreno (C), Caglianone (1b), Pedro Padilla (2b), Benítez
(3b), Ponce (Ss), Luis Belisario (Lf), Alfonso  (Cf) y Ricardo_Salomón (Rf).

** [[http://www.ultimasnoticias.com.ve/noticias/slider/mas-800-tuyeros-reportaron-irregularidades-cajas-clap/][Más de 800 tuyeros reportaron irregularidades con cajas Clap]]
Published: 24 febrero, 2018 6:00 am

Más de 800 familias de los sectores Sabana de La Cruz, San Pablo, Parosca, El
Cerrito y Rangel en Ocumare del Tuy, municipio Tomás Lander (Mir) reportaron que
las cajas Clap contenían alimentos caducados.Carla Pérez, habitante, denunció
que la leche presentaba un color marrón, el arroz, la pasta, los granos y los
otros  productos tenían gorgojo y  carecían de azúcar y harina precocida.Los
afectados devolvieron las cajas a la Proveeduría de Alimentos de Santa
Bárbara.Pérez insistió en que “las autoridades regionales deben investigar la
situación y exigió que el alimento sea distribuido mensualmente”.Héctor
Rodríguez, gobernador de Miranda, acotó que la eventualidad solamente se
registró en el municipio Tomas Lander y que gracias a las familias se rectificó
a tiempo y  se les entregó una nueva caja con productos en buen estado.También
hizo énfasis en que se ha incrementado un 20 % en la distribución de alimentos;
y aclaró que “no es suficiente para cubrir la demanda”, pero “trabajan para  ir
fortaleciendo los Clap”.

** [[http://www.ultimasnoticias.com.ve/noticias/slider-inferior/apagon-afecto-lineas-telefonicas-e-internet/][Apagón afectó líneas telefónicas e Internet]]
Published: 24 febrero, 2018 1:25 pm

.-Nueve estados del occidente del país () quedaron sin electricidad la tarde de
este jueves, por una falla del suministro ocasionada por la caída de la línea
765 de la subestación Yaracuy-La Arenosa.Los 21 municipios zulianos quedaron a
oscuras. En Táchira también, y se vieron afectadas las líneas telefónicas, que
estuvieron caídas hasta ayer, cuando regresó el servicio.Barquisimeto se volvió
un caos hacia las 5 pm, cuando los cruces colapsaron al quedar los semáforos
fuera de juego. El comercio cerró por no poder usar puntos de débito ni
facturar.Igual ocurrió en Mérida, donde la energía volvió pasadas las 4 pm de
ayer.En Yaracuy, la falla de las líneas 1 y 2, que surten a la región, provocó
la “suspensión no planificada de energía eléctrica” en los 14 municipios desde
las 9 pm del jueves hasta las 6 am de ayer.El fluido eléctrico presentó varias
fluctuaciones y las 11:30 am de ayer se registró otro bajón. Las conexiones a
internet y telefonía también se vieron afectadas, reportaron lugareños de la
región occidental.Táchira. Este fue el segundo apagón esta semana en Táchira. La
gobernadora, Laidy Gómez, exigió al Gobierno nacional una explicación oficial.
Indicó que no se generaron emergencias en la región, pero no descarta daños en
equipos.El director de Protección Civil Táchira, Jaibert Zambrano, indicó que
activaron una alerta naranja tras comprobar que las repetidoras de Loma del
Viento no presentaron daños.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/petroleo-venezolano-gano-1584-yuanes-cerro-la-semana-%c2%a5-36925/][Petróleo venezolano ganó 15,84 yuanes y cerró la semana en ¥ 369,25]]
Published: 23 febrero, 2018 2:11 pm

La cesta petrolera venezolana promedió esta semana 369,25 yuanes por barril, lo
que , informó este viernes el Ministerio para el Petróleo.En una base de cambio
de 6,33 yuanes por dólar, , cuando el diferencial era de 6,32 yuanes por
dólar.El crudo nacional mantiene en febrero una media de 367,25 yuanes por
barril.La cesta de referencia de la  (Opep) cerró la semana en 62,74 dólares, lo
que supone un alza de 1,57 centavos en contraste con la cotización de la semana
pasada.En tanto, el precio del barril West Texas Intermediate (WTI), de
referencia en Estados Unidos, escaló 2,02 dólares y cerró en 61,94 dólares,
mientras que el marcador europeo Brent se disparó 2,15 dólares y promedió 65,51
dólares., que subieron más de dos millones de barriles diarios, según
estimaciones de la Administración de Información de Energía (EIA).Pese al
incremento en el bombeo de crudo por parte de Estados Unidos, que ya produce más
de 10 millones de barriles diarios, la Opep y sus 11 socios externos continúan
con la aplicación del acuerdo de recorte para combatir la sobre oferta de crudo.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/maduro-petro-ha-tenido-la-oferta-mas-mil-millones-dolares/][Maduro: El Petro ha tenido la oferta de más de mil millones de dólares]]
Published: 23 febrero, 2018 8:19 pm

El presidente de la República, Nicolás Maduro, expresó este martes a través de
su cuenta en Twitter que “ya tenemos ofertas que superan los mil millones de
dólares”, señaló que los mismos ingresos que van directo a los recursos de la
República.Asimismo, agregó que este jueves la página web tuvo más de 950 mil
visitas. “El Petro es un fenómeno a nivel mundial”, sentenció Maduro.Al tiempo
que sostuvo un encuentro con el Vicepresidente de la República, Tareck El
Aissami, donde estaban explicaron mediante Facebook Live el alcance del Petro y
cómo  pueden ser parte de esta innovación.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/venezuela-fortalece-alianzas-turisticas-colombia-costa-rica-panama/][Venezuela fortalece alianzas turísticas con Colombia, Costa Rica y Panamá]]
Published: 24 febrero, 2018 10:21 am

.- fortalece alianzas en materia turística con para el desarrollo de este sector
y promover el turismo en la costa oriental del país.La ministra venezolana para
el Turismo, , precisó a través de su cuenta en Twitter que la delegación que
participa en la , que se desarrolla en Bogotá, sostuvo un encuentro con un “”
para lograr “eficientes acuerdos para potenciar el destino Mochima, Puerto la
Cruz y Eje Caribe Nororiental”.Asimismo, detalló que se reunieron con
turoperadores de y turoperadores nacionales, para impulsar la conectividad aérea
con la isla de Margarita, en el Estado Nueva Esparta, y facilitar los trámites
de la visa de turismo.El pasado jueves, Venezuela y Ecuador evaluaron en la
misma feria estrategias para mejorar las relaciones en materia turística con el
objeto de promocionar la Ruta Libertador entre ambas naciones.Además, el
viceministro para Turismo, Alí Padrón, sostuvo un encuentro con el presidente de
la aerolínea , Carlos Silva. Allí abordaron la posibilidad de incrementar la
conectividad aérea de AVN

** [[http://www.ultimasnoticias.com.ve/noticias/economia/ministro-quevedo-superviso-optimizacion-procesos-crp/][Ministro Quevedo supervisó optimización de procesos en el CRP]]
Published: 24 febrero, 2018 11:31 am

– De acuerdo a nota de prensa en la continuación de su jornada de trabajo
desplegada este sábado por áreas operacionales del occidente del país, el
ministro del Poder Popular de Petróleo y Presidente de Petróleos de Venezuela
(), realizó este viernes una inspección al Centro de Refinación Paraguaná (),
ubicado en el estado Falcón, para hacer seguimiento a las acciones que se
ejecutan con el objetivo de optimizar las operaciones de esta importante
instalación petrolera.El ministro Quevedo supervisó las unidades medulares de la
entre las que destacan el área de Suministro y la planta de El titular de la
cartera de Petróleo estuvo acompañado por el gerente general del Centro de
Refinación Paraguaná (CRP), Nelson Martínez, el Vicepresidente de Exploración y
Producción, Nelson Ferrer; el subgerente del CRP, Erwin Amaya; el gerente
técnico del CRP, Larry González; el gerente de Operaciones del CRP, Javier
Mendoza, además de trabajadores especialistas, responsables de procesos de
refinación.La actividad se desarrolló como parte de las acciones que contribuyen
al cumplimiento del segundo lineamiento que el presidente de la República,
Nicolás Maduro, instruyó al ministro Quevedo de fortalecer el Sistema de
Refinación Nacional (SRN).

** [[http://www.ultimasnoticias.com.ve/noticias/slider/emprendedores-recibieron-874-millones-bolivares/][Emprendedores recibieron 874 millones de bolívares]]
Published: 24 febrero, 2018 2:22 pm

.- Un total de del Distrito Capital y de los estados Vargas y Miranda recibieron
financiamiento del Banco del Tesoro, por un monto de, para impulsar sus
proyectos productivos.En el acto de entrega de los créditos, realizado en
Caracas, la gerente general de Socialización Bancaria de la referida entidad
bancaria, explicó que esta es la segunda jornada de otorgamiento de
financiamientos que se realiza en lo que va de año.La gerente comentó que se
realizan a través del producto crediticio Tesoro Comunal y el programa
Credisocial Productivo, que están dirigidos a financiar a pequeños productores,
refiere una nota de prensa.Agrega el boletín, que el Banco del Tesoro ofrece a
los emprendedores talleres de inducción financiera, que abarca áreas como
contabilidad básica, bases jurídicas, redes sociales, mercadeo y publicidad.De
igual forma, este viernes 23 de febrero 16 emprendedores de la ciudad de
Barquisimeto realizaron talleres de formación y recibieron financiamiento por un
monto total de Bs. 134.000.000,00 para los sectores de producción, servicio y
comercio.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/jorge-rodriguez-queda-instalado-consejo-defensa-nacional/][Jorge Rodríguez: Queda instalado el Consejo de Defensa Nacional]]
Published: 23 febrero, 2018 3:55 pm

El ministro de Comunicación, Cultura y Turísmo, , anunció este martes luego de
finalizar el consejo de ministros N°318 presidida por el vicepresidente de la
República Tareck El Aissami, que . En el encuentro también participaron todos
los ministros del gabinete ejecutivo y el jefe del Comando Estratégico
Operacional, Remigio Ceballos.“Este consejo para la defensa nacional , que se
llevarán a cabo este fin de semana 24 y 25 de febrero”, comentó Rodríguez.Desde
la sede la vicepresidencia ejecutiva, Rodríguez comentó que el presidente de la
República, Nicolás Maduro, ordenó que se incorporé en estos ejercicios de
defensa nacional un .Con respecto a las decisiones tomadas más temprano por la
presidenta del Consejo Nacional Electoral (CNE), Tibisay Lucena, en relación al
no realizar las elecciones parlamentarias en conjunto a las presidenciales, el
ministro señaló que “acatamos las orientaciones y directrices de los cronogramas
que tenga a bien hacer el Poder Electoral”.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/18-organizaciones-politicas-se-postulado-presidenciales/][18 organizaciones políticas se han postulado para presidenciales]]
Published: 23 febrero, 2018 2:26 pm

La presidenta del Consejo Nacional Electoral , , anunció que un total de para
los comicios presidenciales que se celebrarán el 22 de abril del año en
curso.Asimismo, agregó que “tenemos 18 organizaciones políticas a nivel
nacional, de las cuales y estamos esperando que en el día de hoy y mañana, las
que faltan, puedan traer sus autorizados para postular”.Recordó que y resaltó
que el CNE está listo para recibir estas postulaciones que han entregado los
autorizados para postular.Luego de sostener una reunión con la presidenta de la
Asamblea Nacional Constituyente, , señaló que será revisada y se dará respuesta
la próxima semana. Reseñó AVN.Al respecto, comentó que la reunión fue muy
efectiva y necesaria para tomar las mejores decisiones en beneficio del país.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/venezuela-denuncia-injerencia-del-consejo-permanente-la-oea-ante-presidenciales/][Venezuela denuncia injerencia del Consejo Permanente en la OEA ante presidenciales]]
Published: 23 febrero, 2018 9:17 pm

El embajador de la República Bolivariana de Venezuela ante la Organización de
Estados Americanos (OEA) en Washington, Samuel Moncada, condenó este viernes
lasque a su juicio se realizaron en el Consejo Permanente contra la nación.“Es
un irrespeto a las normas de esta Organización y un  previsto en la legislación
internacional, que se pretenda dirimir los asuntos internos de Venezuela”,
expresó.Moncada opinó que existe una  con algunos países de la región, “mientras
que el que no se alinee con sus intereses pretenden ahorcarlos violando sus
derechos”. Reseñó Globovisión.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/maduro-la-mud-no-estan-pensando-venezuela-sino-los-intereses-partidos/][Maduro a la MUD: No están pensando en Venezuela sino en los intereses de sus partidos]]
Published: 23 febrero, 2018 8:48 pm

El presidente de la República,  se refirió a la (MUD) este viernes a través de
su cuenta en Twitter, y aseguró que .De igual forma, dijo que les refrescaría la
memoria. “¿Qué es lo que quieren?, ¿Querían o no elecciones adelantadas? El
Pueblo quiere elecciones y quiere paz”.Acompañado del tuit, el Jefe de Estado
publicó un video en el que dirigentes de la oposición piden incesantemente un
adelanto de elecciones presidenciales, situación que ahora no respaldan.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/jornada-especial-registro-electoral-exterior-culmina-este-domingo/][Jornada especial de Registro Electoral en el exterior culmina este domingo]]
Published: 23 febrero, 2018 9:07 pm

La Asamblea Nacional Constituyente, Delcy Rodríguez, expresó que “una vez que se
cierre haremos el balance de cómo quedaron los movimientos en el registro, tanto
para los nuevos inscritos como los cambios de residencia, o un tipo de
actualización de los datos”.El  que será utilizado para las elecciones
presidenciales del 22 de abril será auditado este lunes 26 de febrero, de
acuerdo con el calendario publicado por el  para estos comicios.También se
verifican los movimientos en el padrón, como  y cambio de residencia de los
votantes, así como nombres, apellidos y número de cédula de identidad de cada
uno de los electores. Reseñó Globovisión.Esta verificación con la cual se inicia
el proceso de auditorías, 15 en total consiste en la revisión, de manera
exhaustiva, de los archivos que componen el Registro Electoral para determinar
si cumplen con las leyes y las normas electorales vigentes.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/maduro-invito-al-pueblo-acompanarlo-la-inscripcion-candidatura/][Maduro invitó al pueblo a acompañarlo en la inscripción de su candidatura]]
Published: 23 febrero, 2018 7:00 am

– El candidato por el Gran Polo Patriótico (GPP), Nicolás Maduro, (CNE) para los
comicios presidenciales, que se llevarán a cabo este 22 de abril.La invitación
la realizó Maduro a través de una transmisión en Facebook Live, en la que
agradeció el respaldo brindado por el , por los partidos del , el y los
diferentes movimientos sociales.En este sentido, anunció la creación del y
construir el socialismo, reseñó AVN.En este Frente Amplio de la Patria, detalló
Maduro, ““.““, manifestó.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/registro-electoral-sera-auditado-proximo-lunes-26-febrero/][Registro Electoral será auditado el próximo lunes 26 de febrero]]
Published: 23 febrero, 2018 8:13 am

.-, de acuerdo con el calendario publicado para estos comicios por el Consejo
Nacional Electoral (CNE).Esta verificación  consiste en la revisión, de manera
exhaustiva, de los archivos que componen el Registro Electoral para determinar
si cumplen con las leyes y las normas electorales vigentes.También se verifican
los movimientos en el padrón, como nuevos inscritos y cambio de residencia de
los votantes, así como nombres, apellidos y número de cédula de identidad de
cada uno de los electores, informó AVN.En esta revisión, como en todas las
auditorías que se hacen sobre el sistema electoral venezolano, , lo que
garantiza la confiabilidad y transparencia del proceso.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/tibisay-lucena-no-estamos-preparados-para-una-eleccion-conjunta/][Tibisay Lucena: No estamos preparados para una elección conjunta]]
Published: 23 febrero, 2018 1:34 pm

– La presidenta del Consejo Nacional Electoral (CNE), Tibisay Lucena, informó
que las elecciones parlamentarias generales, proceso que incluye se realizarán
luego del comicio presidencial pautado para el próximo 22 de abril.“ “,
sentenció la presidenta del Poder Electoral en compañía de la presidenta de la
Asamblea Nacional Constituyente (ANC), , en la sede principal del organismo
comicial en Plaza Caracas.Por su parte, Delcy Rodríguez, indicó que esta
propuesta de adelantar las elecciones parlamentariasinformó Rodríguez indicó que
la semana entrante la ANC realizará una sesión plenaria para debatir sobre el
adelanto de estos comicios legislativos generales y proponer una fecha para su
ejecución que será presentada al Poder Electoral.

** [[http://www.ultimasnoticias.com.ve/noticias/slider/postulaciones-los-comicios-presidenciales-inician-este-sabado/][Este sábado inicia proceso de postulaciones para los comicios presidenciales]]
Published: 24 febrero, 2018 9:40 am

– Este sábado  inicia el proceso de para los comicios presidenciales, a
efectuarse el próximo 22 de abril, con la inscripción de los , así lo indica el
calendario pautado por el Consejo  Nacional Electoral () en estas
elecciones.Este proceso se llevará a cabo hasta el lunes para su realización
debe accesar al de postulaciones dispuestos en la página del CNE, como lo
establece el artículo 45 de la Ley Orgánica de Procesos Electorales.En dicho
sistema se debe ingresar a la planilla para la postulación, donde se debe
colocar los nombres y apellidos de la persona a postular, En esa planilla,
indica por su parte el Reglamento de la se podrá señalar con cual de los nombres
y apellidos ““, reseñó AVN.Luego de haber realizado estos pasos, deberá imprimir
y suscribir, por triplicado, la planilla de postulación debidamente llenada.El
próximo paso será la presentación de las postulaciones. En esta oportunidad, se
debe cumplir con este paso entre los días 26 y (por ser elecciones
presidenciales).Ante esta instancia, los postulantes tendrán que consignar las
planillas impresas, debidamente acompañadas de recaudos como:–-C, entre otros
recaudos.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/tania-d-amelio-asegura-que-modificacion-de-candidaturas-seran-el-2-de-marzo/][Tania D’ amelio asegura que modificación de candidaturas serán el 2 de marzo]]
Published: 24 febrero, 2018 2:57 pm

e.- así lo informó este sábado la rectora del Consejo Nacional Electoral (), en
la red social de Twitter. en la sede principal del CNE en plaza Caracas. de
febrero previéndose un lapso de dos días para la subsanación de recaudos que
serían el 27 y 28 del corriente.En un tercer tweet indicó que hasta este domingo
25 de febrero se mantendrá la jornada especial de Registro Electoral (RE) en el
extranjero.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/venezuela-e-iran-estrechan-lazos-hermandad-cooperacion-energetica/][Venezuela e Irán estrechan lazos de hermandad y cooperación energética]]
Published: 22 febrero, 2018 4:38 pm

El presidente de Petróleos de Venezuela (Pdvsa), , se reunió este jueves con el
asesor del ministro de Asuntos Exteriores de Irán, , y el embajador de la
República Islámica de Irán, , para estrechar los lazos de hermandad y
cooperación energética entre ambas naciones.“Hoy sostuvimos importante jornada
de trabajo con Mohammad Keshavarz Zadeh, asesor del ministro de Asuntos
Exteriores de Irán y el embajador de la República Islámica de Irán, Mustafá
Alaeí, para fortalecer nuestras relaciones de cooperación energética”, informó
Quevedo a través del Twitter.En otro mensaje difundido en la red social recordó
que el Comandante Hugo Chávez, impulsó las relaciones bilaterales en materia
energética con Irán. .El titular de Pdvsa definió la reunión como un punto
encuentro para fortalecer la capacidad de producción de petróleo.Este miércoles,
en la Casa Amarilla, sede de la Cancillería venezolana, sostuvieron una reunión
el viceministro para Asia, Medio Oriente y Oceanía, , y el embajador Mohammad
Keshavarz, quien también es director general del ministerio de Relaciones
Exteriores iraní para América Latina y el Caribe, con el fin de afianzar las
relaciones políticas y de amistad binacional, como parte de la agenda que cumple
el diplomático persa en Venezuela. Refirió AVN.En el encuentro,  Keshavarz
ratificó, entonces, la disposición de su gobierno de profundizar las relaciones
bilaterales: , manifestó el diplomático iraní, quien también se reunió con la
presidenta de la Asamblea Nacional Constituyente (ANC), Delcy Rodríguez.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/banca-publica-entrego-mas-bs-11-millones-jovenes-emprendedores/][Banca pública entregó más de Bs. 11 millones a jóvenes emprendedores]]
Published: 22 febrero, 2018 4:38 pm

Este jueves fueron entregados más de 11 millones de bolívares por parte del
Banco Bicentenario y el Banco del Tesoro, a para fortalecer a los sectores
productivos que hacen vida en el país.La entrega estuvo a cargo del ministro de
la Juventud y el Deporte, , el presidente del Banco Bicentenario, y la
presidenta del Banco del Tesoro, .Durante el evento, el ministro de la Juventud
y el Deporte ofreció unas palabras en las que agradeció la gestión de la banca
pública para incluir a los jóvenes emprendedores y capaces que sí creen en el
país. Además, aprovecho el momento para explicar quePor su parte, la presidenta
del Banco del Tesoro manifestó que la institución que representa continúa
promoviendo y creyendo en las fuerzas productivas de Venezuela.Asimismo, Pedro
Infante recordó que en el año 2017 fueron entregados 11 mil financiamientos a
los jóvenes del país, y agregó que “Quiero decirle a la juventud que Venezuela
es un país de oportunidades. Nosotros creemos en la juventud que apuestan por la
patria”, expresó.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/preventa-del-petro-durara-30-dias/][Preventa del petro durará 30 días]]
Published: 22 febrero, 2018 5:32 pm

El proceso de, informó este jueves el ministro para la Educación Universitaria,
Ciencia y Tecnología, Hugbel Roa., la cual esta prevista se desarrolle en 15
días, destacó en entrevista a la “Luego de los 45 días que durarán estos dos
procesos, arrancaremos con mucha fuerza para consolidación de todo el subsistema
de intercambio del petro”, aseveró.Desde que se inició la preventa, . “Esta
criptomoneda nace para revitalizar y fortalecer el bolívar”, sostuvo.En este
sentido, ratificó que a diferencia de las más de mil 500 monedas digitales
existentes en el mundo,  del campo 1 del Bloque Ayacucho de la Faja Petrolífera
del Orinoco.Con el respaldo de la riqueza petrolera, refiere Roa, la
criptomoneda venezolana, cuyo valor de un barril de crudo la pone a la
vanguardia de las existentes al convertirla en el criptoactivo más seguro del
mundo, abre el camino a la nueva etapa económica del país.“La nación avanzará en
la cultura del uso de la criptomoneda, es decir, , sino en las distintas
instancias que pueda lograr que un venezolano llegue a un comercio y pague con
criptomoneda”, dijo y será canjeable por dinero fiduciario y otros criptoactivos
a través de casas de intercambio digitales.“. Fortaleceremos la minería digital,
en cada hogar, cada espacio, que la gente pueda tener como minar y asumir el
desarrollo de la minería digital”, aseveró el ministro.Para utilizar este
criptoactivo debe abrirse una billetera digital en la página web del sistema (),
que generará una dirección electrónica donde depositar la criptomoneda, que
podrá adquirirse en función de la capacidad de compra de cada usuario.De acuerdo
con el papel técnico, la tasa entre el petro y el bolívar será determinada a
través de un promedio ponderado por el volumen de operaciones de todas las casas
de cambio autorizadas por el Gobierno nacional.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/claves-conozca-cuales-servicios-podran-ser-pagados-con-el-petro/][CLAVES | Conozca cuáles servicios podrán ser pagados con el petro]]
Published: 22 febrero, 2018 4:45 pm

El petro, la respaldada por las reservas petroleras de la nación, servirá como
mecanismo de pago para una serie de servicios, tanto en el país como en el
exterior.Durante el acto de lanzamiento de este mecanismo de intercambio al
mercado nacional e internacional, el presidente de la República, , destacó que
esta innovación incrementará la entrada de divisas y el crecimiento económico
del país.– Servicios turísticos.– Combustible requerido por las aerolíneas.–
Expendió de gasolina en las estaciones ubicadas en la frontera con Colombia.–
Servicios consulares en todas las embajadas de Venezuela en el mundo.– Las
empresas estatales Petróleos de Venezuela (Pdvsa), Petroquímica de Venezuela
(Pequiven) y la Corporación Venezolana de Guayana (CVG) podrán efectuar un
porcentaje de sus ventas y compras a través del petro.– Actividades financieras
de las cajas de ahorros del país., lo que generará una dirección electrónica que
podrán compartir con quienes quieran transferir esta criptomoneda.Con esa
dirección electrónica, .

** [[http://www.ultimasnoticias.com.ve/noticias/economia/ofertas-negociaciones-torno-al-petro-superan-los-1-000-millones/][Ofertas y negociaciones en torno al petro superan los $ 1.000 millones]]
Published: 23 febrero, 2018 11:13 am

El presidente de la República, Nicolás Maduro, informó este jueves que .En sus
dos primeros días de preventa, se han registrado 292 mil ofertas de intenciones
de compra, de las cuales 36% se ha hecho en dólares, 15% en euros, 18% en
Ethereum y 31% en Bitcoin, precisó el Jefe de Estado en una transmisión de
Facebook Live., entre otros.“Hoy solamente ingresaron a la página para
interconectarse, 950.000 personas, es un fenómeno positivo, un fenómeno
monetario, político, económico, psicológico dentro del camino de la nueva
economía”, comentó.En ese sentido, Recalcó que el objetivo es diversificar la
fuentes de riqueza del país, en esta oportunidad con el petro que próximamente
estará respaldado por oro.
