---
title: "20180225"
date: 2018-02-25T01:10:00-04:00
draft: false
---

* News

** [[http://www.ultimasnoticias.com.ve/noticias/politica/ejecutivo-da-mantenimiento-18-400-escuelas/][Ejecutivo da mantenimiento a 18.400 escuelas]]
Published: 25 febrero, 2018 7:49 pm

Un total de informó el ministro del Poder Popular para la Educación, Elías Jaua Milano.“”, resaltó Jaua durante un contacto transmitido este domingo por Venezolana de Televisión desde la Escuela Técnica Francisco Fajardo, en la parroquia Caricuao, del municipio Libertador, en Caracas.El plan, que se realiza cada dos meses, consta de actividades preventivas de limpieza, pintura, prevención de filtraciones, desmalezamiento, reacondicionamiento de materiales escolares e infraestructura así como el mantenimiento de equipos tecnológicos y sistema eléctrico.En estas jornadas, además de los integrantes de las comunidades educativas se sumaron los voceros de distintos sectores sociales, consejos comunales y comunas que ayudaron en los trabajos para mejorar las infraestructuras educativas de simoncitos, colegios, liceos y escuelas técnicas, favoreciendo a miles de estudiantes en distintos niveles.En este sentido, anunció que para este mes está prevista la inauguración 11 liceos en todo el país.

** [[http://www.ultimasnoticias.com.ve/noticias/slider/venezuela-colombia-chocan-tabloncillo-esta-noche/][Venezuela y Colombia chocan en el tabloncillo esta noche]]
Published: 25 febrero, 2018 11:27 am

– En el papel  saldrá esta noche como favorito ante . Por lo que demostró en los últimos dos juegos de la eliminatoria al el combinado que dirige el argentino Fernando Duró se ve por encima del golpeado equipo cafetero. No obstante, la necesidad de triunfo de los neogranadinos los convertirá en enemigos incómodos en el coliseo Iván de Bedout de Medellín.Los venezolanos, con mayor peso en su baloncesto, han ganado dos de tres juegos en el grupo B del clasificatorio americano. Una de esas victorias fue contra Colombia en el inicio por marcador de 85-71, el pasado 24 de noviembre en el Domo Bolivariano de Barquisimeto. Luego de caer en , la escuadra vinotinto superó el jueves a y de allí su necesidad de ganar hoy (además de ligar un triunfo de los verdiamarillo sobre los australes) para seguir cómodo en el segundo puesto de la llave.“l”, dijo Duró a los medios.Guiados por el experimentado Stalin Ortiz, la escuadra vecina espera sacudirse las tres derrotas que ha sufrido en esta eliminatoria (las otras han sido 74-69 en casa ante Chile y el duro resbalón en su paso por Brasil 84-49).Además de los veteranos Gregory y José Vargas, Heissler Guillent y Néstor Colmenares, en el cuadro nacional se espera por otra exhibición de los jóvenes José Ascanio, Junior Martínez, Yohanner Sifontes y José Bracho.

** [[http://www.ultimasnoticias.com.ve/noticias/deportes/mar-negro-mundo/][Mar Negro para todo el mundo]]
Published: 24 febrero, 2018 6:41 pm

Varias informaciones hicieron pareja la primera válida para el 5 y 6 dominical.Un grueso sector en el Hipódromo La Rinconada se resteaba con Beyeler en la segunda válida, pero se comentaba sobre las posibilidades de Songcat. Pondremos esas dos.. Nos vamos con esa línea en la tercera válida.Entre  debe estar el ganador de la quinta válida. en la sexta válida.Retirados.- 1a.) 8-Liberato; 2a.) 8-Negro Furioso; 5a.) 9-Candy Water; 11a.) 3-Prince Legend; 12a.) 8-The Full Angel y 11-Capitán América)

** [[http://www.ultimasnoticias.com.ve/noticias/deportes/rosalba-maria-las-galopo/][Rosalba María las galopó]]
Published: 25 febrero, 2018 3:16 pm

.- yegua castaña de, por , importada en vientre, nacida y criada en el haras La Invasión, metió tremendo galope en el Clásico Manuel Fonseca Arroyal disputado este domingo en el Hipódromo La Rinconada.Desde los metros iniciales asumió el mando de la carrera, desempeñándose en , con lo que anuló a sus oponentes para ganarles de extremo a extremo y por amplio margen en 1’23”4 para 1.400 metros. O sea que el remate fue de 13” en 200 metros. Fue su segundo triunfo en dos actuaciones para superar los 40 millones y medio de bolívares en premios. La condujo Jorge Urdaneta y la presentó Carlos Alberto Arteaga para el stud Octagon-Rod. El video de la carrera es cortesía del Instituto Nacional de Hipódromos y Video Hípico.

** [[http://www.ultimasnoticias.com.ve/noticias/comunidad/metro-los-teques-estara-operativo-las-900-pm/][Metro los Teques estará operativo hasta las 9:00pm de este domingo]]
Published: 25 febrero, 2018 3:07 pm

.-Este domingo el  prestará sus servicios hasta las de la noche por motivos operacionales.“por lo cual exhortó a los usuarios a tomar sus previsiones, al tiempo que pidió disculpas por las molestias ocasionadas” reseña una nota de prensa.Por su parte el vicepresidente del subterráneo mirandino, , reiteró que el retraso registrado esta semana se debe al robo de cables del que fue víctima el sistema de transporte, reseñó AVN.El sistema Metro Los Teques, ubicado en el estado Miranda, en el centro-norte del país, continúa prestando servicio comercial desde la estación Independencia hasta Las Adjuntas, en Caracas.

** [[http://www.ultimasnoticias.com.ve/noticias/slider-inferior/piden-registrarse-cobrar-bono/][Piden registrarse para cobrar bono]]
Published: 25 febrero, 2018 4:40 pm

ÚN.-Los jefes de cada familia venezolana que han tramitado a través de la aplicación VeQR la protección social de la Gran Misión Hogares de la Patria, deben completar sus datos personales y el registro de sus cargas familiares en el portal web patria.org.ve, para así optar por uno de los bonos de ayuda social implementados por el Gobierno.Así lo informó el vicepresidente de la República, Tareck El Aissami, a través de sus redes sociales.Se pudo conocer que el Gobierno a través de la Gran Misión Hogares de la Patria destinó tres billones 982.649 millones de bolívares, para mejorar la atención y protección de un millón 500.000 familias en todo el país.Los bonos protectores de dicha misión constan de diferentes asignaciones de acuerdo con la cantidad de integrantes que tenga cada familia.Las familias que tengan dos integrantes se le otorgarán 320.000 bolívares mensuales; los hogares con tres personas, 490.000 bolívares; con cuatro integrantes, 660.000 bolívares; mientras que los hogares conformados por cinco integrantes recibirán 830.000 bolívares.Asimismo, a las familias compuestas por seis integrantes se le asignarán 1 millón de bolívares al mes; las conformadas por siete personas se les otorgará 1.170.000; mientras que a los hogares de ocho integrantes se les otorgarán 1.340.000.Las familias con nueve integrantes recibirán un bono al mes de 1.510.000 bolívares y las integradas por 10 personas percibirán 1.680.000 bolívares mensuales. Estos beneficios serán entregados tomando en cuenta los registros del carnet de la patria.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/fotos-perfecta-ejecucion-cerro-ejercicio-militar/][FOTOS | Con “perfecta ejecución” cerró ejercicio militar]]
Published: 25 febrero, 2018 8:07 pm

La Fuerza Armada Nacional Bolivariana , detalló el jefe del Comando Estratégico Operacional (Ceofanb) almirante Remigio Ceballos.Ceballos felicitó a los más de 328 mil milicianos, más de 150 mil efectivos castrenses y personal civil de las organizaciones sociales que participaron en las maniobras.Por otra parte, como parte de las actividades,“Este ejercicio demostró cómo esa unión cívico-militar de la que estamos hablando es fundamental en el sistema defensivo frente a cualquier amenaza”, indicó en declaraciones transmitidas por VTV.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/ejecutivo-aprobo-creacion-la-corporacion-oro-carabobo/][Ejecutivo aprobó creación de la Corporación de Oro en Carabobo]]
Published: 25 febrero, 2018 2:32 pm

– El presidente de la República, , aprobó el punto de cuenta para la creación de una empresa minera en el estado Carabobo, la La firma del punto de cuenta se realizó en el Palacio Presidencial de Miraflores, en Caracas, donde el Mandatario nacional recibió al gobernador de la entidad del centro-norte del país, Rafael Lacava.“Llévate el punto de cuenta creando la corporación de oro, la empresa minera del oro para que en Carabobo entre con toda la fuerza en el desarrollo de minerales. Ganancia para Carabobo. Ganancia para Venezuela”, expresó el Jefe de Estado en el encuentro, tal como difundió Lacava en Twitter.El gobernador agradeció al presidente Maduro este apoyo en favor de los carabobeños.“”, escribió el gobernador.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/productores-del-estado-anzoategui-recibieron-mas-178-millones-bolivares/][Productores del estado Anzoátegui recibieron más 178 millones de bolívares]]
Published: 25 febrero, 2018 11:52 am

.- El  entregó a  del estado Anzoátegui , con el objetivo de impulsar la producción agroidustrial.De acuerdo a nota de prensa de la institución, el presidente del ente bancario, , en compañía del vicepresidente ejecutivo de Banca Comercial, Nader Martelo indicaron que los financiamientos otorgados a los sectores agroindustrial y comercial deben ir directamente a la producción, con La entrega de estos recursos se llevo a cabo en el Complejo Agroindustrial Virgen del Valle, ubicado en Anaco.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/comienza-lapso-avalar-candidaturas/][Comienza lapso para avalar candidaturas]]
Published: 26 febrero, 2018 6:00 am

La Junta Nacional Electoral (JNE) recibirá entre este lunes y martes, los recaudos de aquellos candidatos a la elección del 22 de abril que se hayan postulado a través de la página web durante el fin de semana y hoy, inclusive.El órgano subordinado tendrá entre hoy y el próximo jueves para admitir o rechazar las postulaciones, mientras que los partidos, grupos de electores, así como los ciudadanos que se presenten por iniciativa propia tendrán los días 27 y 28 de este mes para subsanar los recaudos.Hasta el pasado viernes, 15 organizaciones políticas de 18 habían presentado ante el Consejo Nacional Electoral a sus autorizados para postular, según informó la presidenta del organismo comicial, Tibisay Lucena.Las candidaturas podrán ser sustituidas o modificadas el viernes 2 de marzo, “como fecha única”, señaló la rectora principal Tania D’Amelio en su cuenta en Twitter.También este lunes los técnicos de CNE y representantes de los partidos auditarán el registro electoral que se utilizará en las presidenciales.Según una nota de prensa,  relacionados con nuevas inscripciones, depuración de fallecidos, actualización de datos, reubicaciones y personas objetadas e inhabilitadas, entre otros.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/maduro-petro-ha-tenido-la-oferta-mas-mil-millones-dolares/][Maduro: El Petro ha tenido la oferta de más de mil millones de dólares]]
Published: 23 febrero, 2018 8:19 pm

El presidente de la República, Nicolás Maduro, expresó este martes a través de su cuenta en Twitter que “ya tenemos ofertas que superan los mil millones de dólares”, señaló que los mismos ingresos que van directo a los recursos de la República.Asimismo, agregó que este jueves la página web tuvo más de 950 mil visitas. “El Petro es un fenómeno a nivel mundial”, sentenció Maduro.Al tiempo que sostuvo un encuentro con el Vicepresidente de la República, Tareck El Aissami, donde estaban explicaron mediante Facebook Live el alcance del Petro y cómo  pueden ser parte de esta innovación.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/ministro-quevedo-superviso-optimizacion-procesos-crp/][Ministro Quevedo supervisó optimización de procesos en el CRP]]
Published: 24 febrero, 2018 11:31 am

– De acuerdo a nota de prensa en la continuación de su jornada de trabajo desplegada este sábado por áreas operacionales del occidente del país, el ministro del Poder Popular de Petróleo y Presidente de Petróleos de Venezuela (),  realizó este viernes una inspección al Centro de Refinación Paraguaná (), ubicado en el estado Falcón, para hacer seguimiento a las acciones que se ejecutan con el objetivo de optimizar las operaciones de esta importante instalación petrolera.El ministro Quevedo supervisó las unidades medulares de la  entre las que destacan el área de Suministro y la planta de El titular de la cartera de Petróleo estuvo acompañado por el gerente general del Centro de Refinación Paraguaná (CRP), Nelson Martínez, el Vicepresidente de Exploración y Producción, Nelson Ferrer; el subgerente del CRP, Erwin Amaya; el gerente técnico del CRP, Larry González; el gerente de Operaciones del CRP, Javier Mendoza, además de trabajadores especialistas, responsables de procesos de refinación.La actividad se desarrolló como parte de las acciones que contribuyen al cumplimiento del segundo lineamiento que el presidente de la República, Nicolás Maduro, instruyó al ministro Quevedo de fortalecer el Sistema de Refinación Nacional (SRN).

** [[http://www.ultimasnoticias.com.ve/noticias/economia/venezuela-fortalece-alianzas-turisticas-colombia-costa-rica-panama/][Venezuela fortalece alianzas turísticas con Colombia, Costa Rica y Panamá]]
Published: 24 febrero, 2018 10:21 am

.- fortalece alianzas en materia turística con  para el desarrollo de este sector y promover el turismo en la costa oriental del país.La ministra venezolana para el Turismo, , precisó a través de su cuenta en Twitter que la delegación que participa en la , que se desarrolla en Bogotá, sostuvo un encuentro con un “” para lograr “eficientes acuerdos para potenciar el destino Mochima, Puerto la Cruz y Eje Caribe Nororiental”.Asimismo, detalló que se reunieron con turoperadores de y turoperadores nacionales, para impulsar la conectividad aérea con la isla de Margarita, en el Estado Nueva Esparta, y facilitar los trámites de la visa de turismo.El pasado jueves, Venezuela y Ecuador evaluaron en la misma feria estrategias para mejorar las relaciones en materia turística con el objeto de promocionar la Ruta Libertador entre ambas naciones.Además, el viceministro para Turismo, Alí Padrón, sostuvo un encuentro con el presidente de la aerolínea , Carlos Silva. Allí abordaron la posibilidad de incrementar la conectividad aérea de AVN

** [[http://www.ultimasnoticias.com.ve/noticias/economia/escenario-2018-llega-el-08-de-marzo-para-aprender-a-invertir-con-criptomonedas/][Escenario 2018 llega el 08 de marzo para aprender a invertir con criptomonedas]]
Published: 24 febrero, 2018 5:18 pm

El jueves 08 de marzo, Aaron Olmos (economista), John Villar (ingeniero en computación), Roberto Sánchez (ingeniero en computación), Luis Pérez (cryptocurrency trader), Fernando Fernández (abogado), Jaime Sandoval (ingeniero electrónico), Gabriel Jiménez (abogado), John Magdaleno (analista político) y César Aristimuño (economista), son los especialistas invitados para conversar sobre los escenarios económicos en el país. Además, Venezuela se inserta en ese mundo con una apertura a la minería y las transacciones con criptodivisas, incluso con una propia como lo es el petro, señala una nota de prensa. y una detallada explicación de las leyes que regulan esa actividad en el país y otras naciones.La jornada abarcará lo que necesita saber para entrar en el mundo financiero digital. Desde los fundamentos de la tecnología que mueve este mercado hasta cómo hacer operaciones de compra y venta, pasando por los aspectos legales en Venezuela y el mundo, las opciones de criptomonedas y otros activos similares que existen así como las oportunidades del petro.Los participantes conocerán de la mano de expertos, cómo funciona una cadena de bloques (blockchain) y la forma en que las operaciones a través de ellas son públicas, así como el impacto de este nuevo paradigma en la economía local y global.

** [[http://www.ultimasnoticias.com.ve/noticias/slider/arreaza-afirma-canciller-chileno-se-dedico-torpedear-dialogo/][Arreaza afirma que canciller chileno se dedicó a “torpedear” el diálogo]]
Published: 25 febrero, 2018 6:11 pm

El canciller de Venezuela, Jorge Arreaza, denunció este domingo las acciones de su homólogo chileno, Heraldo Muñoz, dirigidas a “torpedear” el diálogo entre el Gobierno y la oposición, que se llevó a cabo en República Dominicana..““, escribió Arreaza en su cuenta Twitter.Muñoz en una entrevista que concedió al diario El Mercurio y que fue publicada este domingo, aseguró de manera injerencista, que “Venezuela no es una democracia”.A finales de enero, el canciller chileno decidió abandonar el acompañamiento al diálogo, alegando un desacuerdo con la realización de la elección presidencial.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/ejecutivo-aprueba-980-mil-euros-sistema-seguridad-del-ceofanb/][Ejecutivo aprueba 980 mil euros para sistema de seguridad del Ceofanb]]
Published: 24 febrero, 2018 5:45 pm

El presidente de la República, Nicolás Maduro,““, resaltó el Jefe de Estado durante el Ejercicio de Acción Defensiva Multidimensional Independencia 2018, desde Fuerte Tiuna, en Caracas., reseñó AVN.“Unión cívico-militar, una poderosa y disciplinada y leal Fuerza Armada con capacidad de penetrar hasta el último punto de la retaguardia enemiga. Queramos paz, independencia, felicidad y prosperidad”, enfatizó Maduro.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/roy-chaderton-quieren-forzar-golpe-estado-venezuela/][Roy Chaderton: “Quieren forzar un golpe de Estado en Venezuela”]]
Published: 25 febrero, 2018 6:30 am

Para el embajador Roy Chaderton Matos, Venezuela tiene capacidad de maniobra a pesar de la dura campaña de Estados Unidos, secundada por “países vasallos” y la oposición nacional que pretenden forzar un golpe de Estado.-Eso es parte de la amenaza permanente de terceros países vasallos del imperio para causar mayor conflicto en Venezuela y forzar el derrocamiento del presidente Maduro. Al no concurrir factores de la oposición muy importantes, aumentan la posibilidad de generar perturbación en Venezuela.-La comunidad internacional son muchos países, Habrá algunos que no reconocerán y continuarán el sabotaje contra Venezuela y el bloqueo, pero también quedarán muchos países amigos que tendrán una visión objetiva de la situación.-No, continuará amenazado. Yo repito lo que he dicho muchas veces: estamos cercados, pero no aislados.-Mantendremos contacto con el resto del mundo, tenemos amigos, alianzas, asociación con otros países, presidimos el Grupo de los No Alineados.-O sea que todavía Venezuela tiene cómo maniobrar-Sí hay juego. Y eso lo digo en serio, no es juego.-Sí, porque tenemos recursos, estamos haciendo bien nuestra política internacional, tenemos capacidad de resistencia y porque somos herederos de un país histórico.-EEUU no es invencible, han fracasado en varias guerras frente a enemigos aparentemente débiles y una guerra con Venezuela sería extremadamente costosa y no sé si se animarán a emprenderla. Creo más bien que ellos preferirán atacar a Venezuela y agredirla hasta el último soldado colombiano.-Pueden lanzar a Colombia a una guerra con Venezuela sin sacrificar sus soldados.

** [[http://www.ultimasnoticias.com.ve/noticias/slider/emprendedores-recibieron-874-millones-bolivares/][Emprendedores recibieron 874 millones de bolívares]]
Published: 24 febrero, 2018 5:39 pm

.- Un total de  del Distrito Capital y de los estados Vargas y Miranda recibieron financiamiento del Banco del Tesoro, por un monto de, para impulsar sus proyectos productivos.En el acto de entrega de los créditos, realizado en Caracas, la gerente general de Socialización Bancaria de la referida entidad bancaria, explicó que esta es la segunda jornada de otorgamiento de financiamientos que se realiza en lo que va de año.La gerente comentó que se realizan a través del producto crediticio Tesoro Comunal y el programa Credisocial Productivo, que están dirigidos a financiar a pequeños productores, refiere una nota de prensa.Agrega el boletín, que el Banco del Tesoro ofrece a los emprendedores talleres de inducción financiera, que abarca áreas como contabilidad básica, bases jurídicas, redes sociales, mercadeo y publicidad.De igual forma, este viernes 23 de febrero 16 emprendedores de la ciudad de Barquisimeto realizaron talleres de formación y recibieron financiamiento por un monto total de Bs. 134.000.000,00 para los sectores de producción, servicio y comercio.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/venezuela-denuncia-pretension-ee-uu-juzgar-presidenciales/][Venezuela denuncia pretensión de EE.UU de juzgar presidenciales]]
Published: 24 febrero, 2018 8:33 pm

A través de un comunicado, Venezuela denunció, ante la comunidad internacional, las pretensiones del régimen de los Estados Unidos (EE.UU) de atentar contra la paz y la estabilidad de Venezuela, al pretender juzgar la elección presidencial del 22 de abril.La Cancillería venezolana indica en el texto que el régimen estadounidense, “en su afán por lograr lo que sus subordinados internos no han obtenido con el apoyo popular a través de elecciones, ahora pretende cuestionar el derecho que tienen los ciudadanos de un país libre, democrático y soberano a decir su futuro sin injerencias de ningún tipo y de forma pacífica”.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/ofertas-negociaciones-torno-al-petro-superan-los-1-000-millones/][Ofertas y negociaciones en torno al petro superan los $ 1.000 millones]]
Published: 23 febrero, 2018 11:13 am

El presidente de la República, Nicolás Maduro, informó este jueves que .En sus dos primeros días de preventa, se han registrado 292 mil ofertas de intenciones de compra, de las cuales 36% se ha hecho en dólares, 15% en euros, 18% en Ethereum y 31% en Bitcoin, precisó el Jefe de Estado en una transmisión de Facebook Live., entre otros.“Hoy solamente ingresaron a la página para interconectarse, 950.000 personas, es un fenómeno positivo, un fenómeno monetario, político, económico, psicológico dentro del camino de la nueva economía”, comentó.En ese sentido, Recalcó que el objetivo es diversificar la fuentes de riqueza del país, en esta oportunidad con el petro que próximamente estará respaldado por oro.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/petroleo-venezolano-gano-1584-yuanes-cerro-la-semana-%c2%a5-36925/][Petróleo venezolano ganó 15,84 yuanes y cerró la semana en ¥ 369,25]]
Published: 23 febrero, 2018 2:11 pm

La cesta petrolera venezolana promedió esta semana 369,25 yuanes por barril, lo que , informó este viernes el Ministerio para el Petróleo.En una base de cambio de 6,33 yuanes por dólar, , cuando el diferencial era de 6,32 yuanes por dólar.El crudo nacional mantiene en febrero una media de 367,25 yuanes por barril.La cesta de referencia de la  (Opep) cerró la semana en 62,74 dólares, lo que supone un alza de 1,57 centavos en contraste con la cotización de la semana pasada.En tanto, el precio del barril West Texas Intermediate (WTI), de referencia en Estados Unidos, escaló 2,02 dólares y cerró en 61,94 dólares, mientras que el marcador europeo Brent se disparó 2,15 dólares y promedió 65,51 dólares., que subieron más de dos millones de barriles diarios, según estimaciones de la Administración de Información de Energía (EIA).Pese al incremento en el bombeo de crudo por parte de Estados Unidos, que ya produce más de 10 millones de barriles diarios, la Opep y sus 11 socios externos continúan con la aplicación del acuerdo de recorte para combatir la sobre oferta de crudo.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/entrevista-maduro-asegura-que-venezuela-se-encuentra-en-una-etapa-de-renovacion/][ENTREVISTA | Sería un error garrafal de la oposición ir a la abstención]]
Published: 25 febrero, 2018 2:34 pm

.- “Estamos dando una batalla histórica por el proyecto bolivariano” respondió Nicolás Maduro ante el señalamiento de que es un presidente impopular hecho por el exparlamentario chileno Marco Enríquez Ominami en entrevista transmitida a través de las pantallas de VTV.Marco Enríquez Ominami (MEO) fue candidato presidencial en la reciente elección ganada por Sebastián Piñera y se le ubica en la izquierda del espectro político de ese país.El entrevistador centró su indagación en la aspiración del Mandatario a ser reelecto y en la visión que se tiene del jefe de Estado en América Latina.“Si en los 31 países de América Latina y el Caribe, las 24 horas del día, durante meses y años repiten en la televisión, en la radio, en la prensa escrita, en las redes sociales, que Maduro es esto, que Maduro es aquello, no te sorprendas que hay un porcentaje de la población que se confunda”, ripostó sobre las matrices de opinión desfavorables que señaló MEO.La situación económica también fue tema de la entrevista.-Venezuela tiene una economía que durante 100 años dependió del petróleo. Y siempre tuvo una inflación superior a la media de América Latina. Con un modelo de importaciones muy dependiente y un peso muy grande de la burguesía comercial, que siempre realizó sus ganancias a partir del dólar petrolero y de la especulación. Con la caída de los precios durante 2015-2016-2017 se instaló un modelo de guerra económica en el país. Único país del mundo que tiene un modelo de establecimiento del precio de su moneda que depende de un marcador totalmente ilegal, totalmente inverosímil, que en Venezuela se conoce como el Dólar Today y que fue instalado como mecanismo de guerra económica para una inflación inducida que ha llegado a niveles terribles. Si no fuera por la protección del empleo, si no fuera por el cuidado especial que hemos tenido en los aumentos salariales periódicos, si no fuera por los distintos mecanismos de protección a la familia a través de las misiones verdaderamente la inflación inducida, brutal que se le ha instalado a Venezuela hubiera tenido estragos graves en la población. El entrevistador llevó la conversación al terreno político y preguntó a Maduro si gobernaría con la oposición tras un eventual triunfo el 22 de abril.“Antes, durante y después voy a llamar al diálogo. Voy a practicar el diálogo. Así lo he hecho. La oposición le tiene miedo al diálogo. Le tiene miedo a la palabra, porque le tiene miedo a los compromisos”.El Mandatario se mostró seguro de la victoria: “Una vez que gane las elecciones presidenciales, que vamos a ganar con un récord de votación, el mundo va a ver como ganamos las elecciones de manera heroica , de manera asombrosa, inmediatamente convocaré al diálogo político, al diálogo social, al diálogo económico nacional.-La oposición lo que tiene es miedo, porque sabe que los números no le dan que el chavismo es hoy una mayoría imposible de revertir y que nosotros en el escenario que sea vamos a tener una gran victoria.En cuanto a la disposición a no votar mostrada hasta ahora por la oposición, Maduro advirtió a sus adversarios que no cometan el “garrafal error histórico de irse a la abstención”.-Te estoy dando cifras certeras, científicas de medición entre el candidato Nicolás Maduro versus cualquier candidato que la oposición lance de manera unitaria, estas cifras las maneja la embajada de Estados Unidos el poder económico del país, la oposición; por eso, ellos se han deslizado hacia un lado malo, peligroso, dañino, autodestructivo de irse al campo de la abstención, del aislacionismo de salirse de la competencia electoral. Pareciera que es la tendencia principal que se le impone a la oposición desde Washington. Como no podemos ganarle a Maduro, Maduro el obrero, el de los humildes, como no le podemos ganar, lo dejamos competir solo. Nosotros vamos a la batalla y vamos a ganar con ellos y sin ellos.Libertad plena. Los derechos humanos en Venezuela y la migración de nacionales fueron también objeto de debate entre el presidente Maduro y Marco Enríquez Ominami–Bueno, tiene 18 años diciendo lo mismo. Y en Venezuela hay una democracia con plenas libertades. Venezuela es un país que tiene problemas, pero tiene muchos menos problemas que esos países que nos critican. Por ejemplo, en España metieron preso a un rapero, tres años y medio porque su canción criticaba a los borbones, al rey. Nadie dijo nada; no quiero imaginar que hubiera sucedido en Venezuela.–-Si me duele todo el que se vaya del país. Porque amo mucho a mi país. Creo que en momentos de dificultades debemos estar juntos trabajando por construir. Aquí están nuestros ancestros enterrados, nosotros tenemos una sangre gloriosa de libertadores. En otros países, Chile por ejemplo, nosotros tuvimos casi 500.000 chilenos en los años 70 y 80 producto de la dictadura. Hemos tenido grandes migraciones de España, Italia, Portugal, del mundo árabe. De Colombia, debe saber Marco Enríquez que en Venezuela viven 5 millones 600 mil colombianos, es la primera vez que se nos presenta el problema de migración de clase media, clase profesional hacia otros países buscando una opción económica. Yo a ellos le extiendo mis manos. He dado instrucciones a la Cancillería para que se establezca una relación de protección, de acompañamiento venezolanista a aquellos migrantes que han partido.A mí me da lo mismo, yo sé quien soy. Sé qué pueblo tenemos y sé para dónde voy. Tengo fe absoluta en la historia de Venezuela, que digan lo que digan, en todo caso, ¿quién me lo dice? Donald Trump, fue Estados Unidos que empezó a remarcarme de dictador. Bueno, si es él quien me remarca de dictador es un elogio y el que lo quiera repetir que lo repita.Un gobierno revolucionario, me comprometo con un gobierno revolucionario. Para todo el país, para el beneficio del país, para la resolución de los problemas, para un nuevo proyecto de economía, para consolidar el sistema de protección social. Para consolidar nuevas formas de democracia.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/jose-vicente-nivel-frustracion-la-oposicion-alarmante/][Rangel: Venezuela cuenta con una oposición atípica, que en lugar de perseverar abraza a la violencia]]
Published: 25 febrero, 2018 10:14 am

.-“” así lo indicó el analista político venezolano José Vicente Rangel en su programa “José Vicente hoy” transmitido por Televen.Al inicio del programa señaló que “el nivel de frustración de la oposición es más que alarmante, es patético”, y que es una situación que nunca antes se había visto en el país.En cuanto a los comicios presidenciales, las cuales serán efectuadas el próximo 22 abril, manifestó que el sector opositor en los últimos años ha exigido elecciones.““, dijo.La falta de programa electoral se debe a “la crisis que la afecta. Le impide elaborar un proyecto más o menos aceptable por la colectividad nacional y sin una línea de acción permanente que genere confianza en sus actores, debido a la dependencia vergonzosa que demuestra permanentemente”.Asimismo, se preguntó “¿“,A su juicio, expresó que si acuden al evento comicial, “corren el riesgo de un desastre total, y si no lo hacen, están planteando la siniestra opción manejada por Estados Unidos, España, Colombia y otros de no reconocer la realización de los comicios y de actuar en función de escalar más las amenazas de bloqueo” contra el país.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/65-los-venezolanos-esta-favor-las-elecciones/][65% de los venezolanos está a favor de las elecciones]]
Published: 25 febrero, 2018 5:00 pm

.-De acuerdo al último estudio con realizado del  de febrero con por la encuestadora , reveló que el de que se celebren los comicios presidenciales el próximo 22 de abril.Asimismo, arrojó que el 71% de los venezolanos está de acuerdo con la participación de la oposición en las próximas elecciones presidenciales, reseñó AVN.Estos resultados los dio a conocer el periodita José Vicente Ragel, en su programa José Vicente Hoy, en el bloque de los Confidenciales trasmitido este domingo por Televén.Cabe destacar, que el 64% de los venezolanos definitivamente irá a votar y un 14% manifestó que probablemente lo hará. Un 11% dijo que no irá y un 9% que es posible que no sufrague, indicó Hinterlaces.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/fotos-venezuela-la-liga-arabe-revisaron-cooperacion-bilateral/][FOTOS | Venezuela y la Liga Árabe revisaron cooperación bilateral]]
Published: 25 febrero, 2018 7:37 pm

El canciller, Jorge Arreaza, revisó  con el secretario general de la Liga Árabe, Ahmed Abul Gheit, la cooperación bilateral, en una visita oficial a Egipto, donde culminó su gira de la Dignidad Sur-Sur.“”, detalló Arreaza a la prensa.““, destacó el canciller venezolano.Ambos funcionarios también conversaron sobre asuntos de Venezuela, entre ellos el proceso electoral presidencial que se efectuará el 22 de abril “y sobre cómo el año pasado pudimos superar momentos difíciles mediante elecciones”, dijo el canciller.En el encuentro, .“La solución a los problemas siempre será el diálogo, la democracia y la paz; no el terrorismo financiado desde Estados Unidos”, puntualizó Arreaza.
