---
title: "20180221"
date: 2018-02-21T07:56:41-04:00
draft: false
---

* News

** [[http://www.ultimasnoticias.com.ve/noticias/slider/activan-dispositivo-inteligencia-metro/][Activan dispositivo de inteligencia en el Metro]]
Published: 21 febrero, 2018 6:30 am

Este lunes en la noche, se activó un dispositivo de seguridad e inteligencia permanente en todos las estaciones del sistema Metro de Caracas para prevenir actos de sabotaje, como los que se han registrado en días recientes, informó el ministro de Transporte, Carlos Osorio.“Estamos desplegados por instrucciones de nuestro presidente Nicolás Maduro con todo un equipo de seguridad , seguimiento, inteligencia, para prevenir y proteger el pueblo ante el saboteo de estas características en nuestras instalaciones del Metro”, dijo en referencia al estallido de una bomba lacrimógena ocurrido el pasado lunes en la estación Capuchino.En día pasados, dos artefactos de este tipo fueron lanzados, uno en la estación Plaza Venezuela y otro, en la estación Petare, ambas de la Línea 1 del subterráneo. Los incidentes generaron pánico entre los usuarios.

** [[http://www.ultimasnoticias.com.ve/noticias/deportes/anibal-sanchez-pacto-los-mellizos-minnesota/][Aníbal Sánchez pactó con los Mellizos de Minnesota]]
Published: 20 febrero, 2018 5:23 pm

Los Mellizos de Minnesota anunciaron que le otorgaron un contrato de un año al diestro venezolano .Según la confirmó una fuente a MLB.com, , pero no es garantizado, lo cual significa que Sánchez tendrá que competir por un puesto en roster durante la pretemporada. El convenio incluye otros $2.5 millones en incentivos.Sánchez, de 33 años de edad, buscará revivir su carrera luego de tener marca de 10-20 con efectividad de 6.09 por los Tigres entre las últimas dos temporadas. No obstante, , en las que registró promedio de carreras limpias de 2.74 y ponchó a 31 bateadores en 23 innings de laborEn sus primeras declaraciones después de oficializar su firma con los Mellizos, Sánchez expresó que estaba emocionado por la oportunidad de luchar por un lugar en la rotación de abridores de su nuevo equipo.“Estoy feliz de estar aquí con este equipo”, dijo el lanzador. Sánchez competirá por un lugar en la rotación contra otros candidatos como Phil Hughes, el dominicano Adalberto Mejía y Tyler Duffey. El manager Paul Molitor afirmó que está pensando utilizar una rotación de cuatro abridores para iniciar la temporada y el puertorriqueño José Berríos, Jake Odorizzi y Kyle Gibson son considerados piezas fijas.Sánchez, quien cumplirá 34 años el 27 de febrero,.“Al final del año todo empezó a funcionar”, dijo Sánchez. “La temporada fue como una montaña rusa, pero terminé fuerte”.“Trabajé mucho durante la temporada muerta para poder retomar mi mecánica sin sentirme adolorido”, añadió Sánchez. “Me siento bien en este momento. Me siento bien de verdad y fuerte. Estoy saludable. Eso es lo importante”.

** [[http://www.ultimasnoticias.com.ve/noticias/slider/caciques-los-punos-listos-ir-heroicos/][Caciques tiene los puños listos para ir contra Heroicos]]
Published: 21 febrero, 2018 6:20 am

Con Yoel Finol -medallista de bronce en Río 2016- y Albert Ramírez en plan estelar, Caciques de Venezuela buscará el viernes barrer a Heroicos de Colombia, en el formato C-1 del Grupo A de la Serie Mundial de Boxeo (WSB, por sus siglas en inglés).Este martes, el equipo nativo dio a conocer a los peleadores que estarán en acción en Barranquilla, en procura de mantenerse en el segundo lugar de la tabla de posiciones, escoltando a los Domadores de Cuba, quienes marchan invictos.Aparte de Finol y Ramírez, subirán al ring Endry Saavedra, Christian Palacio y Luis Jesús Polanco, quien tendrá su primera incursión en este circuito boxístico.Los combates quedaron conformados de la siguiente manera: mosca ligero (49 kg), Yurberjen Martínez (Col) vs Luis Polanco (Ven); gallo (56 kg), John Martínez (Col) vs Yoel Finol (Ven); welter ligero (64 kg), John Gutiérrez Agudelo (Col) vs Christian Palacio; mediano (75 kg), Jorge Vivas (Col) vs Endry Saavedra (Ven) y pesado (91 kg), Julio Deivis (Col) vs Albert Ramírez (Ven). Caciques viene de vencer a Heroicos 3-2.

** [[http://www.ultimasnoticias.com.ve/noticias/slider-inferior/impulsan-la-creacion-espacios-verdes/][Impulsan la creación de espacios verdes]]
Published: 21 febrero, 2018 5:55 am

Este martes fue el lanzamiento del plan deque impulsa la toma de los espacios libres para dedicarlos a las labores de siembra con el fin de  producir tubérculos, vegetales y otros frutos informó el ministro de Agricultura Urbana (Minppau), Freddy Bernal, desde la sede del Ciara.El proyecto va a comenzar por los 250 urbanismos de la Gran Misión Vivienda Venezuela (Gmvv) con el apoyo del Minppau para promover las siembra y producción en la ciudad capital, explicó.Bernal también realizó el despliegue de la flota de camiones de la Ruta Agrourbana que busca facilitar el traslado de carne, pollo, vegetales y tubérculos desde las zonas productivas del país hasta las grandes ciudades.La flota está integrada por ocho camiones con capacidad de cinco toneladas para movilizar cargas que requieren refrigeración o con plataforma para trasladar legumbres o reses en pie, puntualizó.A su vez, explicó que la medida permitirá “comprar directamente a los pequeños y medianos productores”, quienes venden a precios más económicos pero carecen de transporte, lo que los obliga a caer en manos de los especuladores, que inflan los costos de productos por el traslado a las ciudades.Estos vehículos “traerán alimentos frescos, de buena calidad y a precios protegidos por el Estado”, detalló Bernal.Estas acciones están sujetadas a las ferias Agrourbanas y del Campo Soberano organizadas por los ministerios de Alimentación y de Agricultura y Tierra.

** [[http://www.ultimasnoticias.com.ve/noticias/slider/segunda-semifinal-la-ligas-las-americas-se-jugara-regatas/][Segunda semifinal de la Ligas de las Américas se jugará en Regatas]]
Published: 20 febrero, 2018 3:13 pm

La Federación Internacional de Baloncesto () en las Américas confirmó que el , casa del club Regatas, en Corrientes, Argentina, será sede de la. Donde vera acción el quinteto venezolano La semifinal se llevará acabo del 9 al 11 marzo y los rivales que enfrentarán  los dirigidos por el técnico Fernando Duró serán Bauru (Brasil), Estudiantes de Concordia (Argentina) y el anfitrión Regatas Corrientes también de Argentina., un día después a Bauru y cerrarán frente a Regatas. Los mejores dos equipos avanzarán al Final 4 de la competición. Que se celebrará el 24 y 25 de marzo en una sede aún por determinar.La primera Semifinal de la Liga de las Américas 2018 se jugará del 2-4 de marzo en el Polideportivo Roberto Pando y contará con la participación de Ferro (Argentina), Fuerza Regia (México), Mogi das Cruzes (Brasil) y el anfitrión San Lorenzo (Argentina).Venezuela es el actual campeón de la competición y buscará revalidar el título.

** [[http://www.ultimasnoticias.com.ve/noticias/slider-inferior/le-hacen-carinito-18-cdi-caracas/][Le hacen un cariñito a 18 CDI en Caracas]]
Published: 21 febrero, 2018 5:45 am

Continúan los trabajos de rehabilitación y equipamiento de 18 centros que integran la red pública de salud de la Misión Barrio Adentro, ubicados en el Distrito Capital.Las labores de reestructuración son llevadas a cabo por el ministerio de Salud en conjunto con la Fundación de Edificaciones y Equipamiento Hospitalario (Fundeeh), entre los Centros Diagnostico Integral (CDI) que están siendo abordados destacan el CDI María Eugenia González, CDI Dr Alcides Rodríguez “Los Cedros” ambos situados en la parroquia El Valle. Asimismo, se encuentran trabajando en el CDI Ludovico Silva “la Ciudadela” de Santa Rosalía , y  el CDI Los Flores de Catia.Por otro lado, en el Hospital Universitario Dr. Manuel Núñez Tovar en Maturín, Edo. Monagas, fueron rehabilitados de forma integral 8 quirófanos, a través del Plan Quirúrgico Nacional

** [[http://www.ultimasnoticias.com.ve/noticias/politica/arreaza-se-reunio-presidente-guinea-ecuatorial-fortalecimiento-paises/][Arreaza se reunió con el presidente de Guinea Ecuatorial para fortalecimiento entre países]]
Published: 20 febrero, 2018 2:56 pm

.- El canciller de la República,  se reunió este martes con el presidente de Guinea Ecuatorial,  en el marco del fortalecimiento de la  de ambas naciones.“ p“, redactó la cancillería venezolana en la red social Twitter.    Por su parte, Arreaza escribió en la plataforma digital “que el hermano presidente de Guinea Ecuatorial, brindó sus orientaciones en defensa de la soberanía de los pueblos del mundo y manifestó su apoyo a la lucha del presidente  y a la democracia venezolana”.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/cne-realizara-sorteo-de-miembros-de-mesa-el-15-de-marzo/][CNE realizará sorteo de miembros de mesa el 15 de marzo]]
Published: 20 febrero, 2018 5:25 pm

presidenta del Consejo Nacional Electoral (CNE), informó que , debido a que fue una de las condiciones que se ajustaron en el acuerdo por la convivencia y paz consensuado entre el Gobierno y la oposición venezolana en República Dominicana.La información fue emitida este martes al brindar un avance sobre el cronograma electoral, La presidenta del CNE señaló que la Ley del Poder Electoral establece que en el primer trimestre de cada año debe hacerse el sorteo para el servicio comicial en los organismos subalternos, como miembros de mesa, juntas regionales y las municipales.Lucena ratificó que en las jornadas de Registro Electoral (RE) donde fueron activados 530 puntos a lo largo del Estado por motivo de las elecciones presidenciales, Asimismo, para la semana próxima está pautada la inscripción de los postulantes por Internet; La presentación de las postulaciones se hacen ante la Junta Nacional Electoral el 26 de este mes, recordó.Señalando que “, como siempre lo hemos hecho, para darle cumplimiento no solamente al acuerdo de Santo Domingo, sino a las garantías que siempre le damos a los electores y electoras para cada proceso electoral”.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/invitan-la-onu-elecciones-del-22/][Invitan a la ONU para elecciones del 22-A]]
Published: 21 febrero, 2018 6:15 am

La presidenta del Consejo Nacional Electoral (CNE), Tibisay Lucena, informó este martes que enviaron una “solicitud a la Secretaría General de la Organización de Naciones Unidas (ONU) para que se conforme una delegación de acompañamiento y observación electoral, en las elecciones presidenciales del 22 de abril”.Detalló que tendrán un “plan de acompañamiento con expertos electorales, académicos, político y periodistas, que siempre hemos invitado a lo largo de los años. Además de eso, tendremos nuestra misión de acompañamiento técnico, en donde todos los que participen tendrán una oportunidad, como siempre, de estar presentes”, dijo Lucena.Asimismo, afirmó que en cumplimiento con el acuerdo de convivencia por la paz y la democracia en Venezuela planteado en República Dominicana, el CNE realizará auditorías técnicas al sistema electoral con el propósito de garantizar resultados transparentes en los comicios electorales.“El Consejo Nacional Electoral tiene estandarizado una batería de auditorías que se hacen en presencia de los testigos, de las organizaciones con fines políticos, con los observadores nacionales y con los acompañantes internacionales”, recordó.Lucena aseguró que dichos estándares no serán inferiores a los utilizados en las elecciones de los años 2012 y 2015. “Para garantizar procesos electorales transparentes, limpios y resultados perfectos”, manifestó.La máxima representante del órgano electoral señaló que para el 15 de marzo tienen previsto la realización del sorteo de los miembros de mesa, el mismo incluye la auditoría del software y la supervisión del Poder Electoral.De acuerdo con el documento de convivencia democrática, Lucena ratificó el cumplimiento de los 6 puntos que están incluidos en el cronograma electoral como garantía de la elección presidencial que ya fue aprobado por el CNE.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/inicio-formalmente-preventa-del-petro/][Inició formalmente preventa del Petro]]
Published: 20 febrero, 2018 8:00 am

.- Tareck El Aissami, vicepresidente de la República, informó en la madrugada de este martes que  en la página web .“Allí (página web) se detalla todo el procedimiento para la adquisición y comercialización de la criptomoneda”, dijo.Subrayó que que permitirá al país tener mayor independencia.La moneda digital. Fue creada por el Ejecutivo para combatir el bloqueo financiero, captar inversiones y generar un nuevo mecanismo de pago de bienes y servicios.A diferencia de las otras de 1.500 criptomonedas existentes a nivel mundial,  del campo 1 del Bloque Ayacucho de la Faja Petrolífera del Orinoco.Podrá ser usado para adquirir bienes o servicios y será canjeable por dinero fiduciario y otros criptoactivos a través de casas de intercambio digitales.De acuerdo con la información que aparece en la página www.elpetro.gob.ve, la distribución de los fondos que se recauden se repartirá de la siguiente manera: fondos destinados a los desarrollos tecnológicos y esfuerzos de promoción que permitan cumplir con la hoja de ruta anunciada. fondo para la promoción e impulso a las aplicaciones dentro del ecosistema petro, que serán propuestas a través de la Supcacven y seleccionadas por los tenedores de Petro. fondos destinados a inversiones en tecnologías, infraestructuras, zonas especiales y proyectos que contribuyan al avance económico del país, para mejorar la productividad y transparencia en empresas y organismos públicos. destinados a la República por el respaldo otorgado al uso del petro.Horas antes, el presidente Nicolás Maduro, informó a través de Twitter sobre el  la cual permitirá fortalecer la economía del país.El Jefe de Estado en su mensaje anunció que a las 12:30 de la medianoche de Venezuela y 12:30 del mediodía en China se produciría el esperado estreno de la innovadora criptomoneda nacional.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/anc-aprobo-acuerdo-constituyente-respaldo-al-petro/][ANC aprobó Acuerdo Constituyente en Respaldo al Petro]]
Published: 20 febrero, 2018 6:27 pm

La Asamblea Nacional Constituyente (), aprobó este martes de manera unánime un , criptomoneda venezolana, respaldada por las riquezas petroleras de la nación., primera vicepresidenta de la ANC, tras la lectura del texto debatido este martes en la sesión plenaria realizada en el Salón Protocolar del Palacio Federal Legislativo, manifestó que el lanzamiento inédito, histórico y revolucionario de El Petro se hace por la , por parte de naciones adversas al Gobierno de Venezuela.“Queda aprobado este Acuerdo en el cual los Constituyentes y las Constituyentes, como voceros y voceras del pueblo soberano, respaldamos a la República Bolivariana de Venezuela en esta iniciativa”.“Venezuela, una vez más, a la vanguardia de los derechos del pueblo del mundo”, agregó.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/foro-esmecha-la-criptomoneda/][Foro ÚN “esmecha” la Criptomoneda este miércoles]]
Published: 20 febrero, 2018 5:04 pm

Las criptomonedas son  sin depender de ninguna institución bancaria. , que facilita efectuar transacciones entre dos personas desde cualquier parte del mundo con el uso de Internet.Esta realidad se hace cada vez más próxima a Venezuela desde que el presidente de la República, , anunció la creación del petro, una criptomoneda que ., director de la marca Últimas Noticias. Al foro asistirán , Superintendente de los Criptoactivos y Actividades Conexas; , presidente de la Asociación Nacional de Criptomoneda; , economista y exministro de Industrias Básicas; y , profesor de la Universidad Simón Bolívar y miembro del Observatorio Nacional del Blockchain., y que la tecnología Blockchain penetrará en el país este año para agregar otra forma de manejar el dinero. , ubicado al final de la avenida Rómulo Gallegos, cruce con 4ª avenida, en La Urbina. Iniciará a partir de las 9 am y culminará a las 12:30 pm. El foro será transmitido en vivo a través de www.ultimasnoticias.com.ve y por las redes sociales de la empresa.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/juan-arias-petro-facilitara-comercio-exterior/][Juan Arias: El petro facilitará el comercio exterior]]
Published: 20 febrero, 2018 5:19 pm

Tras el inicio de la preventa del petro, el ministro de Industrias Básicas, , aseguró este martes que la criptomoneda venezolana facilitará las operaciones comerciales con el exterior., expresó Arias en entrevista a Aseguró que el país enfrenta una guerra contra su economía, promovida desde el exterior, lo cual ha generado “desequilibrios importantes”. En ese sentido, considera que el petro “ayudará muchísimo a salir de estos problemas”.El ministro explicó que  Por su parte, si la operación se realiza en petros, nadie conocerá quién se encuentra detrás de la compra., aseveró.Asimismo, señaló que es “muy difícil” bloquear al petro porque “está al margen del sistema bancario. No te pueden cerrar la cuenta (…) Si alguien descubre cómo sabotear las criptomonedas, Wall Street sería el más interesado en sabotearlas todas”.Catalogó como positivo el hecho de que la minería de criptomonedas desde Venezuela se ha convertido en un atractivo para muchos inversionistas extranjeros debido a la regulación existente en el país, sin embargo, instó a también invertir en la economía real.“La economía financiera no es la que va a salvar al mundo, sino la economía real. Hay que producir“, dijo.El ministro Arias destacó que las , lo cual no significa que todas las empresas crecieron, ya que se trata de un promedio.Señaló que hay empresas que tuvieron un crecimiento de 300%, particularmente las empresas dirigidas por trabajadores. También indicó que existen compañías en las que se sustituyeron las importaciones y “dieron un salto” trabajando con materia prima nacional.Además indicó que funcionó es restablecimiento de los canales de comercialización con otras empresas públicas que ahora hacen compras importantes.“Estoy satisfecho del heroísmo productivo de nuestro pueblo. ”, puntualizó.

** [[http://www.ultimasnoticias.com.ve/noticias/slider/ejecutivo-certifico-mas-5-mil-mineros-explotar-la-criptmoneda-petro/][Ejecutivo certificó más de 5 mil mineros para explotar la criptmoneda El Petro]]
Published: 20 febrero, 2018 9:08 pm

El presidente de la República, Nicolás Maduro, ordenó este martes la certificación de más de 5.000 mineros para explotar la criptomoneda El Petro en el país.“El Superintendente Carlos Vargas me esta pidiendo la autorización para emitir los tramites a todo los mineros de que se han inscrito en el Blockchain nacional y cumpliendo las normas de seguridad ¡Autorizado!”, expresó el mandatario nacional desde el Palacio de Miraflores.El Superintendente Carlos Vargas,durante su intervención mostró al país la maquinaria de la minería digital, y destacó que”estas maquinas son de fabricación china, pero tenemos maquinas que son ensambladas en Venezuela”.Asimismo, fue inaugurada la Primera Petro Escuela de Granja Laboratorio en el Estado Aragua. La inauguración la realizó el ministro para la Juventud y Deporte, Pedro Infante.Desde las primeras horas de este martes cuando se inició la preventa del petro “hemos logrado la intención de compra de la preventa de 477 millones de yuanes, lo cual significa 596 millones de euros y 735 millones de dólares. Tremendo golpe. ¡Un Bombazo!”, sentenció Maduro.El anuncio lo hizo este martes el jefe de Estado, Nicolás Maduro, desde el Palacio de Miraflores.Manifestó que el Gobierno Nacional ha entregado al Petro la cantidad 5 mil millones de Barriles de Petróleo del Campo n° 1 del Bloque Ayacucho. “Es el Oro Negro”. Reseñó AVN.

** [[http://www.ultimasnoticias.com.ve/noticias/slider/claves-asi-se-puede-comprar-la-petromoneda/][CLAVES | Así se puede comprar la Petromoneda]]
Published: 20 febrero, 2018 10:50 am

El 3 de diciembre del 2017, mediante una rueda de prensa, el presidente Nicolás Maduro anunció la creación de una criptomoneda que estaría respaldada en los recursos naturales del país: el petróleo, el oro, el gas y los diamantes.Por su parte, según el  (Hoja Blanca), documento que detalla las especificaciones técnicas y operativas de esta criptomoneda, cada petro es divisible en hasta 100 millones de unidades, por lo que los ciudadanos podrán adquirir incluso una cienmillonésima (0,00000001) parte, que recibirá el nombre de “mene”. Ingresa en la página de registro que encontrarás en la web del Petro . Una vez culminado el registro, la misma enviará un mensaje a tu correo electrónico con el link para acceder a tu . Ingrese al correo electrónico y accede al link que te redirigirá al sitio de descarga de tu wallet.Descarga el archivo comprimido () desde la dirección web .Descomprime el archivo y ejecútelo. Abre la wallet, haz click en Sign UP, luego en Simple Wallet, presiona Ready y por último haz click en Next. Colócale nombre a tu wallet y asigna una contraseña. Haz click Understood.Oprima en Download Wallet y guarde tu wallet en un lugar seguro (disco duro externo o dispositivo de almacenamiento que vayas a mantener bajo tu protección). Haz click en Show Private Key. Copie la Clave Semilla () y guárdelo en un lugar seguro. Oprima en / Have my Private Key and Password. Haz click en / Agree. Seleccione el wallet en el desplegable de Select Wallet, introduce tu contraseña y oprime Sign In. Haz click arriba a la derecha sobre Account. Donde dice Address aparece la dirección del Wallet, este es el dato que debes enviar para recibir los Petros (PTR). Descarga el manual para el comprador del Criptoactivo El Petro

** [[http://www.ultimasnoticias.com.ve/noticias/slider/infografia-petro-estara-al-alcance-todos-los-venezolanos/][INFOGRAFÍA | Petro estará al alcance de todos los venezolanos]]
Published: 18 febrero, 2018 6:00 am

El 3 de diciembre del 2017, el presidente Nicolás Maduro anunció la creación de una criptomoneda que estaría respaldada en los recursos naturales del país: el petróleo, el oro, el gas y los diamantes.Según sus declaraciones, esta iniciativa surge con la finalidad de evadir las sanciones impuestas por el Gobierno de Estados Unidos sobre nuestra economía. La idea concreta es que a través de esta plataforma digital pueda transferirse el dinero sin que pase por una institución bancaria que impida o sabotee la operación.Además de que se podrán efectuar pagos de deuda o facilitar las importaciones con cualquier mercado internacional sin impedimentos o regulaciones, postularon al petro como una herramienta financiera de utilidad para el desarrollo económico del país que estaría al alcance de todos los ciudadanos.El superintendente de los Criptoactivos y Actividades Conexas de Venezuela, Carlos Vargas, anticipó que los venezolanos tendrían acceso al petro para llevar a cabo sus actividades financieras cotidianas, y ratificó que la preventa inicial será el martes 20.“Van a existir muchos comercios que aceptarán el petro o cualquier criptomoneda. En un futuro corto los venezolanos podrán comprar en la panadería con petros”, aseguró.En un primer momento, el precio del petro se había establecido como una preocupación. El presidente Maduro había anunciado que cada unidad de la criptomoneda tendría el valor del barril de petróleo según la cesta de crudos venezolana, que este año ha promediado los 60 dólares. Sin embargo, se reveló que el sistema será más flexible.Según el White Paper (Hoja Blanca), documento que detalla las especificaciones técnicas y operativas de esta criptomoneda, cada petro es divisible en hasta 100 millones de unidades, por lo que los ciudadanos podrán adquirir incluso una cienmillonésima (0,00000001) parte, que recibirá el nombre de “mene”.Para poseer petros, será necesario tener una billetera virtual, tal y como indica la Gaceta Oficial Extraordinaria N° 6.346, que en su artículo 5 dice: “el tenedor de cada petro será poseedor de una billetera virtual, la cual será de su entera responsabilidad, así como todos los riesgos asociados al manejo y custodia de la misma”. Se podrá acceder a esta billetera a través de un computador, un celular o cualquier otro dispositivo inteligente que permita utilizar la plataforma donde estará almacenado el dinero. La novedad de este nuevo esquema económico, es la plataforma tecnológica que sostiene a las criptomonedas. El Blockchain o Cadena de Bloques es un sistema virtual que funciona como un banco administrado equitativamente por todos los usuarios.Las transacciones se realizan de manera inmediata y los datos quedan almacenados en las computadoras o dispositivos de todos los usuarios del sistema, por lo que se genera un registro histórico de las operaciones que no puede ser intervenido, alterado ni borrado de ninguna manera.“La tecnología Blockchain es perfectamente auditable, totalmente transparente, y eso es una garantía significativa del nacimiento en confianza de este instrumento”, explicó Vargas durante el acto de instalación del Observatorio Nacional del Blockchain. Otro campo que se abre con la aparición de las criptomonedas en Venezuela es el de la minería digital. Esta actividad funciona mediante computadores especializados que dedican su capacidad para verificar los códigos y datos de las transacciones que se registran en la plataforma Blockchain y validarlas para darle protección al sistema.Como recompensa por desarrollar este trabajo, los mineros adquieren comisiones de las criptomonedas que minen.La minería requiere gran cantidad de electricidad e Internet para llevarse a cabo, y Venezuela se ha convertido en uno de los países ideales para desarrollar dicha actividad por el bajo costo de dichos servicios. “Tenemos la electricidad más barata del mundo. Fabricar desde el punto de vista de la minería un Bitcoin en China cuesta $1.560; en Venezuela esto vale entre 100 y 200”, señaló el Superintendente.El Observatorio Nacional del Blockchain abrió el Registro de Mineros de Criptomonedas a fin de poseer los datos de quienes practican esta actividad y los equipos que utilizan.Minar permite la posibilidad de adquirir divisas de manera directa al cambiar las criptomonedas obtenidas.El constituyente Darío Omar lo ve como una oportunidad. “A través de la minería los empresarios venezolanos tendrán la oportunidad de obtener sus propias divisas y tener libertad financiera sin depender de que el Estado o el Banco Central adjudiquen divisas. Cualquier venezolano que adquiera las máquinas podrá tener divisas y acceder a diferentes plataformas para comprar por Internet”, dijo. lLas emisiones del petro están controladas por el Estado. Según el White Paper, en una primera instancia se venderían 38.400.000 “tokens”, moneda virtual que luego sería convertida en petro. El 28 de marzo culminaría esta preventa. El 29 de marzo se efectuaría la oferta inicial de 44 millones de petros, y la venta se extendería hasta que se agote esa cantidad. Los 17 millones 600 mil petros restantes los retendrá la Superintendencia. Los petros solo podrán ser adquiridos mediante dólares u otras criptomonedas. El documento que detalla la operatividad del petro indica que “el Estado no podrá hacer nuevas emisiones del criptoactivo petro”. No obstante, persiste la duda sobre si se harán otras emisiones a futuro con otros recursos, como diamantes, coltán, oro y gas.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/llegan-insumos-dializadores-garantizar-tratamiento-pacientes/][Llegan insumos y dializadores para garantizar tratamiento a pacientes]]
Published: 19 febrero, 2018 8:54 am

Insumos médicos y dispositivos dializadoresDestacó que con esta adquisición se busca fortalecer el Sistema Público Nacional de Salud con apoyo del Plan Barrio Adentro 100%.““, reseñó López.En enero pasado, el presidente de la República, Nicolás Maduro, aprobó recursos dirigidos a la adquisición de insumos para las máquinas diálisis del banco de sangre del Instituto Venezolano de los Seguros Sociales (IVSS).

** [[http://www.ultimasnoticias.com.ve/noticias/slider/canciller-llega-nigeria-parte-gira-pueblos-del-sur/][Venezuela y Nigeria se comprometen en la recuperación del mercado petrolero]]
Published: 19 febrero, 2018 9:21 am

El ministro para Relaciones Exteriores, Jorge Arreaza, Arreaza fue recibido por su homólogo nigeriano, Geoffrey Onyeama, quien ratificó el compromiso de trabajar junto a Venezuela para enfrentar los grandes desafíos en materia de seguridad y en la recuperación del mercado de petróleo.““, dijo Onyeama en declaraciones ofrecidas junto a Arreaza.“”, destacó. en pro de los pueblos.“Apoyaremos al Gobierno de Venezuela, promoveremos el incremento de nuestra relación comercial y esperamos que la paz y la estabilidad reinen pronto en el país porque Venezuela posee grandes potencialidades y recursos que creemos deben estar al servicio del pueblo venezolano”, añadió el canciller Geoffrey Onyeama y al mismo tiempo agradeció la visita de Arreaza.

** [[http://www.ultimasnoticias.com.ve/noticias/slider-inferior/banco-bicentenario-entregara-50-mil-creditos-2018/][Banco Bicentenario entregará 50 mil créditos en el 2018]]
Published: 18 febrero, 2018 9:02 pm

Como parte de las políticas sociales creadas por el Comandante Supremo, Hugo Chávez e impulsadas por el jefe de Estado Nicolás Maduro, , aseguró este sábado que en su afán de fortalecer la economía comunal y productiva del país, la entidad bancaria espera entregar 50 mil créditos a los venezolanos durante el 2018.En su participación especial en el Primer Taller de Formación de los Bancos de Comuna realizado en la sede del Centro Nacional de Formación Simón Rodríguez, ubicado en San Antonio de Los Altos, estado Miranda, Pérez Abad ratificó el compromiso de la institución que preside para el financiamiento económico del poder popular organizado.La autoridad calificó como victoriosa la gestión del Banco Bicentenario del Pueblo en 2017: “En el 2016, cuando yo no estaba en el banco, se entregaron 2.200 millones en proyectos sociales; pero en 2017, cuando llegué a la institución, se otorgaron 109 mil millones para inversiones sociales. Y ahora, en 2018, esperamos entregar 50 mil créditos con requisitos mínimos para nuevos proyectos”.Miguel Pérez Abad informó que en los próximos días el BBDP iniciará un plan piloto en Maturín, estado Monagas, que consiste en el pago a los pensionados según el día que corresponda el último número de su cédula de identidad “con el propósito de minimizar el problema del efectivo”.“Luego vamos a Zulia y después lo vamos a estandarizar en Venezuela, de tal manera que podamos corregir algunas desviaciones que se puedan conseguir”, manifestó. En ese sentido, la máxima autoridad del BBDP alertó acerca del fenómeno denominado “abuelitos bachaqueros”.Pérez Abad recalcó que el Banco Bicentenario del Pueblo es la institución que más paga pensiones a los adultos mayores y jubilados del país, con un total de 1.400 mil pensionados que reciben una atención priorizada y especial en las agencias de la institución bancaria.El presidente del Primer Banco Socialista de la Nación, resaltó la importancia del Taller de Formación de los Bancos de Comuna para un nuevo modelo económico en Venezuela. “Hoy más que nunca estamos obligados a lograrlo (…) y por eso el propósito de estos encuentros es saber que vamos en la dirección correcta, a pesar de las dificultades”, agregó.

** [[http://www.ultimasnoticias.com.ve/noticias/economia/expocaprina-2018-exhibira-fortalezas-la-produccion-ovina-falcon/][ExpoCaprina 2018 exhibirá fortalezas de la producción ovina en Falcón]]
Published: 19 febrero, 2018 5:51 pm

Este próximo 24 de febrero en Coro, capital del estado Falcón, se realizará , un evento organizado por la secretaría Agrícola de la entidad para estimular la producción caprina y ovina de la región, que ocupa los primeros lugares en estos rubros.La autoridad colectiva de Agricultura y Tierras, Felipe Suárez, explicó que productores elite de la región tomaron la iniciativa de esta actividad con el fin de “Los productores asumen el rol protagónico de lo que vienen haciendo, mostrando la transformación positiva del sector, a pesar de la coyuntura actual, hay municipios emblemáticos de la región con grandes aportes”, dijoPrecisó que , entre otros.Mencionó que , que espera impactar positivamente en los planes de producción de todos los derivados de estos rubros.“Visionamos un centro de mejoramiento genético, un centro de producción gastronómica; en fin, tantas cosas que pueden impulsarle haciéndolas parte de nuestra cultura por ser este tipo de animales parte de nuestra identidad”, dijo.Recordó que en 2017 cerca de 500 mil cabezas de animales caprinos y 100 mil ovinos estaban censados, cifra que prevén multiplicar durante 2018. Para ello, la entidad cuenta con 13.000 unidades de producción operativas en toda la región para explotar esta actividad ícono de la zona occidental.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/cabello-propondra-efectuar-elecciones-parlamentarias-las-presidenciales/][Cabello propondrá efectuar elecciones parlamentarias con las presidenciales]]
Published: 20 febrero, 2018 10:23 am

.- El constituyente Diosdado Cabello propondrá realizar conjuntamente las elecciones de la Asamblea Nacional (AN) junto con las presidenciales.““, expuso este martes en una entrevista concedida al programa Dando y Dando, transmitido por Destacó que esta propuesta que se presentará ante la Asamblea Nacional Constituyente surge ante el vacío político que representa la actual inacción del parlamento venezolano.““, insistió.Cabello también considera factible ajustar los tiempos administrativos que se requieren para que el Poder Electoral pueda organizar esta consulta electoral, informó AVN.“Todavía aquí no se han hecho las postulaciones oficiales a candidatos presidenciales, creo que por el interés de la patria habría que revisar todo, ¿Qué es lo que falta? (se preguntó) postular candidatos a diputados: son 165 candidatos por los estados, no veo ningún inconveniente, sería un elemento dinamizador de la política”, agregó.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/consultores-30-11-72-los-venezolanos-votara-presidenciales/][Consultores 30.11: 72% de los venezolanos votará en presidenciales]]
Published: 20 febrero, 2018 8:42 am

.-  revela un estudio realizado por la encuestadora Consultores 30.11.A los encuestados se les consultó su intención de voto y 64,3% respondió que seguro que votará y que es probable que vote 8,2%, lo que suma 72%, puntualizó el director de la encuestadora, Germán Campos, en entrevista este martes en el programa , de Venezolana de Televisión.El estudio realizado entre el 1º al 6 de febrero revela que un  mientras que actores de la oposición, como el empresario Lorenzo Mendoza, Henri Falcón, Henry Ramos Allup y Claudio Fermín, El presidente Maduro también destacó con un  del elector frente a un candidato de la Mesa de la Unidad Democrática (MUD), que obtuvo 26,8%, y un candidato independiente, que registró 10,5%, informó La encuesta también reveló que un Acerca de la aprobación a la convocatoria de la Asamblea Nacional Constituyente (ANC) a las elecciones presidenciales en el primer cuatrimestre del año: 62,7% está de acuerdo.Por otra parte, el estudio evaluó la percepción de los ciudadanos con respecto al modelo político de preferencia y cuáles actores identifican con el pasado político del país, sobre lo cual un 64,7% considera que la MUD representa el pasado mientras que 65,2% estima que cualquier candidato de la MUD entra en esta categoría.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/cne-invito-a-la-onu-a-conformar-mision-de-acompanamiento-y-observacion-para-presidenciales/][CNE invitó a la ONU a conformar misión de acompañamiento y observación para presidenciales]]
Published: 20 febrero, 2018 1:24 pm

La presidenta del Consejo Nacional Electoral (CNE), Tibisay Lucena, informó la realización de las auditorías a todo el sistema comicial con los , condición que se ajusta al acuerdo por la convivencia y la paz consensuado por Gobierno y oposición venezolana en República Dominicana.De igual forma, Lucena confirmó que  (ONU) , previstos para el 22 de abril.La petición, que se ajusta a lo previsto en la legislación venezolana en materia electoral,, entre septiembre y febrero.Además, se propone que el coordinador de la misión sea , uno de los acompañantes del proceso de diálogo, tal como lo establece el Acuerdo de Convivencia Democrática por Venezuela, diseñado en territorio dominicano.Asimimsmo, informó que el próximo 15 de marzo se hará el sorteo de los votantes que prestarán servicio electoral en los venideros comicios presidenciales.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/ltibisay-lucena-el-cne-no-ha-recibido-propuesta-para-realizar-elecciones-parlamentarias/][Tibisay Lucena: El CNE no ha recibido propuesta para realizar elecciones parlamentarias]]
Published: 20 febrero, 2018 1:45 pm

.- La presidenta del Consejo Nacional Electoral (CNE), Tibisay Lucena, confirmó que el Poder Electoral no ha recibido una propuesta oficial sobre la realización de elecciones parlamentarias junto con las elecciones presidenciales en conjunto para el próximo 22 de abril.“reiteró Lucena durante una rueda de prensa en la que confirmó la realización de las auditorías a todo el sistema comicial con los Estas declaraciones fueron otorgadas luego que el constituyente  (AN) junto con las presidenciales.““, expuso este martes en una entrevista concedida al programa Dando y Dando, transmitido por Destacó que esta propuesta que se presentará ante la Asamblea Nacional Constituyente surge ante el vacío político que representa la actual inacción del parlamento venezolano.

** [[http://www.ultimasnoticias.com.ve/noticias/slider/anc-evalua-propuesta-ley-poder-legislativo/][ANC evalúa propuesta de Ley para el Poder Legislativo]]
Published: 20 febrero, 2018 11:53 am

La presidenta de la Asamblea Nacional Constituyente, Delcy Rodríguez,Rodríguez responde de esta manera a sobre realizar las elecciones para escoger a los diputados de la Asamblea Nacional, conjuntamente con los comicios presidenciales del próximo 22 de abril.

** [[http://www.ultimasnoticias.com.ve/noticias/politica/padrino-lopez-reitera-compromiso-la-fanb-la-proteccion-del-voto/][Padrino López reitera compromiso de la Fanb en la protección del voto]]
Published: 20 febrero, 2018 12:42 pm

El ministro de Defensa, Vladimir Padrino López, ratificó este martes el compromiso de la Fuerza Armada Nacional Bolivariana (Fanb) con la protección del libre ejercicio del voto, de cara a las elecciones presidenciales del 22 de abril próximo.““, señaló durante un balance que ofreció sobre el Ejercicio de Acción Defensiva Independencia 2018 que se desarrolla a lo largo de esta semana.Alertó que el país está atravesando una agresión sin precedentes frente a agentes imperiales, que además hay sectores que quieren abandonar los caminos democráticos, reseñó AVN.““, subrayó.“Se ha venido imponiendo la política de la guerra. Lo que no se ha logrado por la vía electoral, pacífica y democrática en estos 19 años es porque hay un sistema fuerte” destacó.“Todos los venezolanos debemos insistir: o es la Patria o es la nada. Nosotros apostamos a la patria, la paz, al sistema democrático, susceptible de libertad. Las armas democráticas del siglo XXI son los votos y el diálogo”, dijo Padrino López desde Fuerte Tiuna, Caracas.

* Codes

=date -f "" "`date`"=t
