name: deploy document with hugo

on:
  push:
    branches:
      master

env:
  SSH_ACTIONS: false
  DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
  ARGS: "-e -c -r"
  SERVER_PORT: "22"
  FOLDER: "./docs/site/public/"
  SERVER_IP: "xunqinji.top"
  USERNAME: "root"
  SERVER_DESTINATION: "/www/wwwroot/pro.xunqinji.top/"

jobs:
  build-hugo-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SSH connection to Actions
        uses: P3TERX/debugger-action@master
        if: env.SSH_ACTIONS == 'true'
      - name: Hugo Actions
        uses: srt32/hugo-action@v0.0.3
