name: deploy document with hugo

on:
  push:
    branches:
      source

jobs:
  build-hugo-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: source
      - name: SSH connection to Actions
        uses: P3TERX/debugger-action@master
        if: env.SSH_ACTIONS == 'true'
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.11
        with:
          hugo-version: latest # optional, default is latest
          extended: false # optional, default is false
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          branch: master # optional, default is master
          force: true # optional
          directory: "./public" # optional, default is .
